import 'package:wallet_wise/widgets/app_bar/custom_app_bar.dart';import 'package:wallet_wise/widgets/app_bar/appbar_leading_image.dart';import 'package:wallet_wise/widgets/app_bar/appbar_subtitle_thirteen.dart';import 'models/profile_settings_model.dart';import 'package:flutter/material.dart';import 'package:wallet_wise/core/app_export.dart';import 'provider/profile_settings_provider.dart';class ProfileSettingsScreen extends StatefulWidget {const ProfileSettingsScreen({Key? key}) : super(key: key);

@override ProfileSettingsScreenState createState() =>  ProfileSettingsScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => ProfileSettingsProvider(), child: ProfileSettingsScreen()); } 
 }
class ProfileSettingsScreenState extends State<ProfileSettingsScreen> {@override void initState() { super.initState();Future.delayed(const Duration(milliseconds: 3000), (){
NavigatorService.popAndPushNamed(AppRoutes.onboardingoneScreen, );}); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(extendBody: true, extendBodyBehindAppBar: true, appBar: _buildAppBar(context), body: Container(width: SizeUtils.width, height: SizeUtils.height, decoration: BoxDecoration(gradient: LinearGradient(begin: Alignment(0.5, 0), end: Alignment(0.5, 1), colors: [appTheme.yellow800, appTheme.lightGreen900])), child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 16.v), child: Column(children: [Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: _buildFrameNinetyEight(context, language: "lbl_currency".tr, english: "lbl_usd".tr)), SizedBox(height: 32.v), Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: _buildFrameNinetyEight(context, language: "lbl_language".tr, english: "lbl_english".tr)), SizedBox(height: 32.v), Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: _buildFrameNinetyEight(context, language: "lbl_theme".tr, english: "lbl_dark".tr)), SizedBox(height: 32.v), Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: _buildFrameNinetyEight(context, language: "lbl_security".tr, english: "lbl_fingerprint".tr)), SizedBox(height: 32.v), Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: _buildFrameNinetyEight1(context, about: "lbl_notification".tr)), SizedBox(height: 33.v), Divider(color: theme.colorScheme.primary.withOpacity(0.38)), SizedBox(height: 39.v), Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: _buildFrameNinetyEight1(context, about: "lbl_about".tr)), SizedBox(height: 32.v), Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: _buildFrameNinetyEight1(context, about: "lbl_help".tr)), SizedBox(height: 5.v)]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 64.v, leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgMagiconsGlyph, margin: EdgeInsets.only(left: 16.h, top: 16.v, bottom: 16.v)), centerTitle: true, title: AppbarSubtitleThirteen(text: "lbl_settings".tr)); } 
/// Common widget
Widget _buildFrameNinetyEight(BuildContext context, {required String language, required String english, }) { return Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.end, children: [Padding(padding: EdgeInsets.only(top: 3.v), child: Text(language, style: CustomTextStyles.titleMediumPrimary_1.copyWith(color: theme.colorScheme.primary))), Spacer(), Padding(padding: EdgeInsets.only(top: 5.v), child: Text(english, style: CustomTextStyles.titleSmallLightgreen90001.copyWith(color: appTheme.lightGreen90001))), CustomImageView(imagePath: ImageConstant.imgMagiconsGlyphPrimary, height: 24.adaptSize, width: 24.adaptSize)]); } 
/// Common widget
Widget _buildFrameNinetyEight1(BuildContext context, {required String about, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 1.v, bottom: 2.v), child: Text(about, style: CustomTextStyles.titleMediumPrimary_1.copyWith(color: theme.colorScheme.primary))), CustomImageView(imagePath: ImageConstant.imgMagiconsGlyphPrimary, height: 24.adaptSize, width: 24.adaptSize)]); } 
 }
